# The cntent of this file should be taken from k8s cluster that user want the framework to interact with.
apiVersion: v1
clusters:
- cluster:
    certificate-authority-data: <ca-cert-data>
    server: https://<k8s-server-ip>:6443
  name: default
contexts:
- context:
    cluster: default
    user: default
  name: default
current-context: default
kind: Config
preferences: {}
users:
- name: default
  user:
    client-certificate-data: <cert-data>
    client-key-data: <ket-data>
